collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6075504
  brandStrength: 0.7849463
  rhythmicContrast: 0.8351254
  brandColors:
    - '#020203'
    - '#31879B'
    - '#044B65'
    - '#807F88'
    - '#65422F'
  lightness: 0.7805884
typography_spectrum: 0.389459
layout_spectrum: 0.8404851
name: Lots of Little
